2019-07-07 18:15:37,460 ERROR: Exception on /register [POST] [in /home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lomolo/Projects/microblog/app/routes.py", line 41, in register
    if form.validate_on_submit():
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask_wtf/form.py", line 101, in validate_on_submit
    return self.is_submitted() and self.validate()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 310, in validate
    return super(Form, self).validate(extra)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/wtforms/form.py", line 152, in validate
    if not field.validate(self, extra):
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 206, in validate
    stop_validation = self._run_validation_chain(form, chain)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/wtforms/fields/core.py", line 226, in _run_validation_chain
    validator(form, self)
  File "/home/lomolo/Projects/microblog/app/forms.py", line 15, in validate_username
    user=User.query.filter_by(username=username.data).first()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3222, in first
    ret = list(self[0:1])
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3012, in __getitem__
    return list(res)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3324, in __iter__
    return self._execute_and_instances(context)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/orm/query.py", line 3349, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1248, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1466, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 399, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1244, in _execute_context
    cursor, statement, parameters, context
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 550, in do_execute
    cursor.execute(statement, parameters)
OperationalError: (sqlite3.OperationalError) no such table: user
[SQL: SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user 
WHERE user.username = ?
 LIMIT ? OFFSET ?]
[parameters: (u'jane', 1, 0)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-07-07 18:16:12,735 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 18:16:18,585 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 18:16:26,010 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 18:19:51,683 ERROR: Exception on /unfollow/john [GET] [in /home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lomolo/Projects/microblog/venv/local/lib/python2.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/lomolo/Projects/microblog/app/routes.py", line 110, in unfollow
    user=User.query.filter_by(username=username),first()
NameError: global name 'first' is not defined
2019-07-07 18:21:05,759 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 18:48:08,705 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 20:35:53,986 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 20:37:11,029 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 20:43:55,277 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 20:44:32,597 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 20:46:02,259 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 23:49:10,165 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 23:49:35,260 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-07 23:49:42,420 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:01:52,271 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:02:24,460 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:02:46,649 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:02:54,026 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:03:05,109 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:08:01,774 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:19:51,222 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:21:47,700 INFO: Mcroblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:23:43,972 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:23:56,388 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:25:26,587 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:25:34,299 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:25:44,295 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:25:51,709 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 00:26:05,492 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 10:23:50,128 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 10:24:05,284 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 10:24:45,172 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 10:24:52,340 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 17:25:03,698 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 17:25:19,357 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 18:43:18,916 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 18:47:15,182 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
2019-07-08 19:10:16,245 INFO: Microblog startup [in /home/lomolo/Projects/microblog/app/__init__.py:49]
